wallXml = "http://www.videoportal.sf.tv/videowallajax"
thumbnailPath = "http://www.sf.tv/piccache/webtool/data/pics/vis/%s/%s/%s/%s_w_h_m.jpg"
informationBySegment = "http://www.videoportal.sf.tv/cvis/segment/%s/filename?nohttperr=1;omit_video_segments_validity=1;omit_related_segments=1;nearline_data=1"
identUrl = "http://%s/fcs/ident"
streamUrl = "rtmp://%(server)s:1935/%(app)s?_fcs_vhost=%(vhost)s&akmfv=1.7 playpath=mp4:%(video)s swfurl=http://www.videoportal.sf.tv/flash/videoplayer.swf swfvfy=1"
